import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import LoginModal from '@/components/LoginModal';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [userId, setUserId] = useState('');
  const [password, setPassword] = useState('');
  return (
    <>
      <Head>
        <title>Infinite Scrolling</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex items-center justify-center bg-gray-500 h-screen">
        <LoginModal
          userId={userId}
          password={password}
          setPassword={setPassword}
          setUserId={setUserId}
        />
      </main>
    </>
  );
}
